name: Run pytest

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Ollama
      run: |
        curl -sS https://ollama.com/install.sh | bash
        export PATH=$HOME/.ollama:$PATH

    - name: Clear pip cache
      run: |
        rm -rf ~/.cache/pip

    - name: Preload SentenceTransformer model
      run: |
        pip install sentence-transformers
        python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"


    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
        pip install -e .

    - name: Run template tests
      run: |
        pytest tests --maxfail=1 --disable-warnings -q
